# Usa una imagen base de Java
FROM eclipse-temurin:21-jdk

# Crea el directorio de la app
WORKDIR /app

# Copia el JAR compilado
COPY target/*.jar app.jar

# Expone el puerto (ajústalo según el microservicio)
EXPOSE 8084

# Comando para arrancar
CMD ["java", "-jar", "app.jar"]