FROM eclipse-temurin:21-jdk

WORKDIR /workspace
COPY . .
RUN chmod +x mvnw
RUN ./mvnw clean install -DskipTests -pl microservicios/microservicio-comun
RUN ./mvnw clean package -DskipTests -pl microservicios/microservicio-videojuegos -am
RUN ls -la microservicios/microservicio-videojuegos/target/

CMD ["java", "-jar", "/workspace/microservicios/microservicio-videojuegos/target/microservicio-videojuegos-1.0.0.jar"]